### ISSUE TITLE
postgres schema 연동 시 Connection 오류나는 현상

### ISSUE THREAD

**Issue by kor-Chipmunk** [mash-up-kr/node-11th-toy-mashupAlpineClub#15]
## 배경
현재 DB에서 `toy` 라는 이름으로 스키마가 생성됨.
그러나 toy 스키마로 연결을 시도하면, 아래와 같은 오류 발생함.

현재는 `public` 스키마에 작성 중.
RDS 에서 자체적으로 막아놓는 건지 궁금함.

## 오류 내용

.env.local 파일에 아래와 같이 `DATABASE_SCHEMA` 추가
```
...
DATABASE_SCHEMA=toy
```

`src/config/configuration.ts` 에도 아래와 같이 적용
```ts
import 'dotenv/config';
export default () => ({
  database: {
    host: process.env.DATABASE_HOST || '',
    user: process.env.DATABASE_USER || '',
    name: process.env.DATABASE_NAME || '',
    password: process.env.DATABASE_PASSWORD || '',
    port: process.env.DATABASE_PORT || '',
    schema: process.env.DATABASE_SCHEMA || '',
  },
});
```

`src/app.module.ts` 에도 아래와 같이 `schema` 필드로 대입함
```ts
TypeOrmModule.forRootAsync({
  imports: [ConfigModule],
  inject: [ConfigService],
  useFactory: (configService: ConfigService) => ({
    type: 'postgres',
    host: configService.get('database.host'),
    port: configService.get('database.port'),
    username: configService.get('database.user'),
    password: configService.get('database.password'),
    database: configService.get('database.name'),
    schema: configService.get('database.schema'),
    entities: [__dirname + '/**/*.entity.{js,ts}'],
    namingStrategy: new SnakeNamingStrategy(),
    synchronize: true,
  }),
}),
```

```
[Nest] 41120  - 2021. 09. 11. 오전 11:18:54   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (5)...
QueryFailedError: relation "users" already exists
    at QueryFailedError.TypeORMError [as constructor] (/Users/seonjaekim/Documents/Workspace/node-11th-toy-mashup-alpine-club/src/error/TypeORMError.ts:7:9)
    at new QueryFailedError (/Users/seonjaekim/Documents/Workspace/node-11th-toy-mashup-alpine-club/src/error/QueryFailedError.ts:9:9)
    at PostgresQueryRunner.<anonymous> (/Users/seonjaekim/Documents/Workspace/node-11th-toy-mashup-alpine-club/src/driver/postgres/PostgresQueryRunner.ts:258:19)
    at step (/Users/seonjaekim/Documents/Workspace/node-11th-toy-mashup-alpine-club/node_modules/typeorm/node_modules/tslib/tslib.js:143:27)
    at Object.throw (/Users/seonjaekim/Documents/Workspace/node-11th-toy-mashup-alpine-club/node_modules/typeorm/node_modules/tslib/tslib.js:124:57)
    at rejected (/Users/seonjaekim/Documents/Workspace/node-11th-toy-mashup-alpine-club/node_modules/typeorm/node_modules/tslib/tslib.js:115:69)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

**Comment by turastory** [comment]
DB 유저 postgres의 스키마 접근 권한이 없어서 발생한 문제였습니다.

스키마 접근 권한 확인
```
select distinct *
from information_schema.usage_privileges;
```

스키마 접근 권한 부여
```
grant usage on schema toy to postgres;
grant all privileges on all tables in schema toy to postgres;
grant all privileges on all sequences in schema toy to postgres;
```

권한 부여했는데 한 번 확인 부탁드립니다.

**Comment by turastory** [comment]
테스트로 테이블 하나 만들었는데 잘 되는 것 같습니다.
```
create table toy.test_table
(
    id varchar(11) not null
);
```

![image](https://user-images.githubusercontent.com/8898339/132935944-14cb9754-a61d-4e50-b70d-bfb87cd27d49.png)

**Comment by kor-Chipmunk** [comment]
굳굳 테스트해보고 답글 달게욥!

**Comment by kor-Chipmunk** [comment]
굳굳 테스트해보고 답글 달게욥!

**Comment by kor-Chipmunk** [comment]
@turastory @colin950 잘 됩니다! 관련 설정 PR 로 열겠습니다.
